### ISSUE TITLE
[ENHANCEMENT] Zoom on GeoJson layer new features 

### ISSUE THREAD

**Issue by sebastienbinda** [MizarWeb/MizarWeb.github.io#4]
We need to have on automatic zoom to the barycentre of the added features on a geojson layer.

**Comment by J-Christophe** [comment]
After checking, it is already implemented here : 
https://github.com/MizarWeb/Mizar/blob/68f516296f48db8b7214a7035e5bab80f416fe94/src/Layer/GeoJsonLayer.js#L133-L152

However, to use the computed values, you need to send an event : 
https://github.com/MizarWeb/Mizar/blob/68f516296f48db8b7214a7035e5bab80f416fe94/src/Context/AbstractContext.js#L660 

Therefore, send an event : 
layer.publish(Mizar.EVENT_MSG.LAYER_VISIBILITY_CHANGED, layer);
or use the following method (the method will call the the right event):
layer.setVisible(true)

**Comment by sebastienbinda** [comment]
Thanks it works nice.
I added the line bellow after the featureCollection is added to the layer
```js
layer.addFeatureCollection(geoJson)
layer.publish(Mizar.EVENT_MSG.LAYER_VISIBILITY_CHANGED, layer)
```
